# Generated by Django 3.0.3 on 2020-06-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_idnum',
            field=models.CharField(default='No data', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(default='No data', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=12),
        ),
    ]
