# Generated by Django 3.0.3 on 2020-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200627_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_idnum',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_last_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
