# Generated by Django 3.0.3 on 2020-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200630_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_branch',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
