# Generated by Django 3.0.3 on 2020-06-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200630_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=20, null=True)),
                ('exam_date', models.DateTimeField(verbose_name='exam date')),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='exam_title',
        ),
        migrations.AddField(
            model_name='score',
            name='exam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Exam'),
        ),
    ]
