# Generated by Django 3.0.3 on 2020-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200630_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(blank=True, verbose_name='exam date'),
        ),
    ]
