# Generated by Django 3.0.3 on 2020-06-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200630_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
