# Generated by Django 3.0.3 on 2020-06-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
