# Generated by Django 3.0.3 on 2020-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='field1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='field2',
            field=models.CharField(default=models.CharField(max_length=20, null=True), max_length=100),
        ),
    ]
