# Generated by Django 3.0.3 on 2020-07-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_score_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clas',
            new_name='Classroom',
        ),
    ]
