# Generated by Django 3.0.3 on 2020-07-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20200703_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_branch',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Subject'),
        ),
    ]
