# Generated by Django 3.0.3 on 2020-07-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20200703_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_full_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
